/*!
 * \file
 * \brief 
 * \author Maciej
 */

#ifndef BACKGROUNDESTIMATOR_HPP_
#define BACKGROUNDESTIMATOR_HPP_

#include "Base/Component_Aux.hpp"
#include "Base/Component.hpp"
#include "Base/DataStream.hpp"
#include "Base/Property.hpp"
#include "Base/EventHandler2.hpp"

#include <opencv2/opencv.hpp>


namespace Processors {
namespace BackgroundEstimator {

/*!
 * \class BackgroundEstimator
 * \brief BackgroundEstimator processor class.
 *
 * 
 */
class BackgroundEstimator: public Base::Component {
public:
	/*!
	 * Constructor.
	 */
	BackgroundEstimator(const std::string & name = "BackgroundEstimator");

	/*!
	 * Destructor
	 */
	virtual ~BackgroundEstimator();

	/*!
	 * Prepare components interface (register streams and handlers).
	 * At this point, all properties are already initialized and loaded to 
	 * values set in config file.
	 */
	void prepareInterface();

protected:

	/*!
	 * Connects source to given device.
	 */
	bool onInit();

	/*!
	 * Disconnect source from device, closes streams, etc.
	 */
	bool onFinish();

	/*!
	 * Start component
	 */
	bool onStart();

	/*!
	 * Stop component
	 */
	bool onStop();


	// Input data streams
	Base::DataStreamIn<cv::Mat> in_img;

	// Output data streams
	Base::DataStreamOut<cv::Mat> out_img;

	// Handlers

	// Properties
	Base::Property<std::string> method;
	Base::Property<int> rate;
	Base::Property<bool> automatic;
	
	int reset_flag;
	
	// Handlers
	void onNewImage();
	void reset();

	cv::Mat fgMaskMOG2; //fg mask fg mask generated by MOG2 method
	cv::Ptr<cv::BackgroundSubtractor> pMOG; //MOG2 Background subtractor
	cv::Ptr<cv::BackgroundSubtractor> pMOG2; //MOG2 Background subtractor
	cv::Ptr<cv::BackgroundSubtractor> pCNT; //CNT Background subtractor
	cv::Ptr<cv::BackgroundSubtractor> pGMG; //GMG Background subtractor
	cv::Ptr<cv::BackgroundSubtractor> pSub; //MOG2 Background subtractor

};

} //: namespace BackgroundEstimator
} //: namespace Processors

/*
 * Register processor component.
 */
REGISTER_COMPONENT("BackgroundEstimator", Processors::BackgroundEstimator::BackgroundEstimator)

#endif /* BACKGROUNDESTIMATOR_HPP_ */
